### ISSUE TITLE
minio port 9000 seems to clash with docker k8s on Mac

### ISSUE THREAD

**Issue by AshSilver** [sergioenterprisedb/cnp-dr-demo#4]
It appears that one of the K8s components on a Mac uses port 9000.  Suggest config for minio to use different port.  I could be wrong, but I am running -p 9200:9000 to avoid the clash and redirecting cluster1.yaml and cluster2.yaml to port 9200. IDK if it will work but I am a noob. :)

**Comment by sergioenterprisedb** [comment]
You can modify start_minio_docker_server.sh with your configuration:
```
# Docker Server
docker run -p 9000:9000 -p 9001:9001 \
           -e MINIO_ROOT_USER=admin \
           -e MINIO_ROOT_PASSWORD=password \
           minio/minio server /data \
           --console-address ":9001"
```
