### ISSUE TITLE
config_cnp.sh and kubectl-cnpg

### ISSUE THREAD

**Issue by AshSilver** [sergioenterprisedb/cnp-dr-demo#5]
kubectl-cnpg failed to install in previous step of install_cnp.sh which calls config_cnp.sh

**Comment by AshSilver** [comment]
line of config_cnp.sh has "kubectl-cnpg" - it should read:
export version=`kubectl-cnp version | awk '{ print $2 }' | awk -F":" '{ print $2}'`

**Comment by sergioenterprisedb** [comment]
Fixed
```
export version=`kubectl cnp version | awk '{ print $2 }' | awk -F":" '{ print $2}'`
```
